using CL.PostgreSQL.Core;
using CL.PostgreSQL.Models;
using Xunit;
using Xunit.Abstractions;

namespace PostgreSQL.Tests;

// A single test that prints the full generated DDL for a deliberately awkward entity.
// Kept so the real output can be eyeballed (dotnet test -l "console;verbosity=detailed")
// rather than only inferred from targeted assertions, and so the whole script is checked
// for MySQL residue in one place.

[Table(Name = "kitchen_sink", Schema = "inventory", Comment = "Everything at once")]
[CompositeIndex("ix_ks_sku_region", "sku", "region")]
[CompositeIndex("uq_ks_code", "code", Unique = true)]
public sealed class KitchenSink
{
    [Column(Name = "id", Primary = true, AutoIncrement = true)]
    public int Id { get; set; }

    [Column(Name = "code", NotNull = true)]
    public string Code { get; set; } = "";

    [Column(Name = "sku", Size = 64, NotNull = true, Index = true)]
    public string Sku { get; set; } = "";

    [Column(Name = "region", Size = 16)]
    public string? Region { get; set; }

    [Column(Name = "price", DataType = DataType.Numeric, Precision = 12, Scale = 4)]
    public decimal Price { get; set; }

    [Column(Name = "external_id", Unique = true)]
    public Guid ExternalId { get; set; }

    [Column(Name = "created_utc", DefaultValue = "now()", Comment = "insert time")]
    public DateTime CreatedUtc { get; set; }

    [Column(Name = "updated_utc", OnUpdateCurrentTimestamp = true)]
    public DateTime UpdatedUtc { get; set; }

    [Column(Name = "payload", DataType = DataType.Jsonb)]
    public string? Payload { get; set; }

    [Column(Name = "owner_id")]
    [ForeignKey("owners", "id", OnDelete = ForeignKeyAction.Cascade)]
    public int OwnerId { get; set; }

    [Column(Name = "tags")]
    public string[]? Tags { get; set; }

    [Column(Name = "deleted_utc")]
    public DateTime? DeletedUtc { get; set; }
}

public sealed class DdlSnapshotTest
{
    private readonly ITestOutputHelper _out;
    public DdlSnapshotTest(ITestOutputHelper output) => _out = output;

    [Fact]
    public void Generated_ddl_is_postgresql_throughout()
    {
        var sql = new SchemaAnalyzer().GenerateCreateTable(typeof(KitchenSink));
        _out.WriteLine(sql);

        // No MySQL construct may survive anywhere in the script.
        foreach (var bad in new[]
                 {
                     "`", "ENGINE=", "DEFAULT CHARSET", "utf8mb4", "AUTO_INCREMENT",
                     "UNIQUE KEY", "COMMENT=", "ON UPDATE CURRENT_TIMESTAMP",
                     "TINYINT", "DATETIME", "LONGTEXT", "UNSIGNED", "MODIFY COLUMN",
                     "CHANGE COLUMN", "ADD INDEX",
                 })
        {
            Assert.DoesNotContain(bad, sql, StringComparison.OrdinalIgnoreCase);
        }

        // And the PostgreSQL-specific shapes must all be present.
        Assert.Contains("CREATE TABLE IF NOT EXISTS \"inventory\".\"kitchen_sink\"", sql);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("\"external_id\" uuid", sql);
        Assert.Contains("\"payload\" jsonb", sql);
        Assert.Contains("\"tags\" text[]", sql);
        Assert.Contains("\"price\" numeric(12,4)", sql);
        Assert.Contains("\"created_utc\" timestamp with time zone", sql);
        Assert.Contains("REFERENCES \"inventory\".\"owners\" (\"id\") ON DELETE CASCADE", sql);
        Assert.Contains("CREATE INDEX IF NOT EXISTS \"ix_ks_sku_region\"", sql);
        Assert.Contains("CONSTRAINT \"uq_ks_code\" UNIQUE (\"code\")", sql);
        Assert.Contains("COMMENT ON COLUMN", sql);
        Assert.Contains("CREATE TRIGGER", sql);

        // Nullable/non-nullable handling.
        Assert.Contains("\"code\" character varying(255) NOT NULL", sql);
        Assert.Contains("\"deleted_utc\" timestamp with time zone", sql);
        Assert.DoesNotContain("\"deleted_utc\" timestamp with time zone NOT NULL", sql);
    }

    [Fact]
    public void Schema_crc_is_stable_across_calls()
    {
        // The CRC gates whether a sync runs at all, so it must not depend on reflection order.
        var analyzer = new SchemaAnalyzer();
        var first = analyzer.ComputeSchemaCrc(typeof(KitchenSink));
        var second = analyzer.ComputeSchemaCrc(typeof(KitchenSink));
        Assert.Equal(first, second);
        Assert.Equal(8, first.Length);
    }
}
