name: Tests

on:
  push:
    branches:
      - main
      - prerelease
    paths:
      - 'CL.*/**'
      - 'tests/**'
      - 'Directory.Build.*'
      - '.github/workflows/test.yml'
      - '.github/workflows/ci-tests.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  suite:
    uses: ./.github/workflows/ci-tests.yml
